// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv7jiC_TXeNJZtHm98UeFeAcDONJR4RnY',
    appId: '1:312702665775:web:aaffa6f62ba6c7ab1a72da',
    messagingSenderId: '312702665775',
    projectId: 'moonflow2004',
    authDomain: 'moonflow2004.firebaseapp.com',
    storageBucket: 'moonflow2004.firebasestorage.app',
    measurementId: 'G-DHVY04ML9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4kdkI8qZN59tkzan1QJ-liN7Z9Z_E3N8',
    appId: '1:312702665775:android:072da738c811da7f1a72da',
    messagingSenderId: '312702665775',
    projectId: 'moonflow2004',
    storageBucket: 'moonflow2004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAGSlDRB_NXAIciJlLriZxl-SiXxepMBw',
    appId: '1:312702665775:ios:1387b5b005a266c51a72da',
    messagingSenderId: '312702665775',
    projectId: 'moonflow2004',
    storageBucket: 'moonflow2004.firebasestorage.app',
    iosBundleId: 'com.example.navigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAGSlDRB_NXAIciJlLriZxl-SiXxepMBw',
    appId: '1:312702665775:ios:1387b5b005a266c51a72da',
    messagingSenderId: '312702665775',
    projectId: 'moonflow2004',
    storageBucket: 'moonflow2004.firebasestorage.app',
    iosBundleId: 'com.example.navigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv7jiC_TXeNJZtHm98UeFeAcDONJR4RnY',
    appId: '1:312702665775:web:5532e67225b4b95b1a72da',
    messagingSenderId: '312702665775',
    projectId: 'moonflow2004',
    authDomain: 'moonflow2004.firebaseapp.com',
    storageBucket: 'moonflow2004.firebasestorage.app',
    measurementId: 'G-KH6X6HJE2Y',
  );
}
