import 'package:flutter/material.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'language': 'Language',
      'home': 'Home',
      'profile': 'Profile',
      'settings': 'Settings',
      'logout': 'Logout',
      'dark_mode': 'Dark Mode',
      'change_period': 'Change Period',
      'save': 'Save',
      'cancel': 'Cancel',
      'edit': 'Edit',
      'selected': 'Selected',
      'period': 'Period',
      'ovulation': 'Ovulation',
      'fertile': 'Fertile',
      'welcome': 'Welcome',
      'enter_cycle_info': 'Lets better understand your cycle!',
      'learn_about_cycle': 'Learn about your cycle',
      'next': 'Next',
      'back': 'Back',
      'close': 'Close',
      'select_date': 'Select date',
      'invalid_number': 'Please enter a valid number.',
      'fill_fields': 'Please fill in all fields.',
      'enter_period': 'Enter period',
      'reset': 'Reset',
      'last symptom entry': 'Last symptom entry',
      'view': 'View',
      'enter_symptom': 'Enter symptom',
      'enter_symptom_hint': 'Click here to add your symptoms',
      'cycle_duration': 'Cycle duration',
      'period_length': 'Period length',
      'next_ovulation': 'Next ovulation',
      'fertile_window': 'Fertile window',
      "last_period": "Last period",
      "to": "to",
      "next_period_in": "Next period in {days} days.",
      "you_are_in_your_period": "You are in your period.",
      "today_is_ovulation_day": "Today is your ovulation day.",
      "you_are_fertile_in": "You are fertile. Ovulation in {days} days.",
      "days_until_next_period": "Days until next period: {days}",
      'forum': 'Forum',
      'newest': 'Newest',
      'oldest': 'Oldest',
      'most_liked': 'Most Liked',
      'most_commented': 'Most Commented',
      'my_posts': 'My Posts',
      'no_posts': 'No Posts... Post something',
      'type_message': 'Type a message...',
      'error': 'Error',
      "search_posts": "Search posts...",
      "chat_title": "Moonflow Chat Bot",
      "chat_hint": "Hi I'm MoonFlowBot. Enter your question",
      "error_loading_response": "Error loading response",
      "partner_mode": "Partner Mode",
      "partner_title": "MoonFlow for Partners",
      "partner_welcome": "Glad you're here 💜",
      "partner_mood_prompt": "Choose the mood your partner will see:",
      "mood_stars": "Starry Sky ✨",
      "mood_sunset": "Sunset 🌅",
      "mood_glitch": "Futur Glitch 🌐",
      "generate_code": "🔗 Generate Connection Code",
      "your_partner_code": "Your code for the shared mode:",
      "share_code_message":
          "Share this code with your partner to let them see how you feel 💫",
      "preview_partner_see": "This is how it will look on your partner’s phone",
      'no symptoms saved': 'No symptoms saved.',
      'physical': 'Physical',
      'emotional': 'Emotional',
      'discharge': 'Discharge',
      'flow': 'Flow',
      'enter symptoms': 'Enter symptoms',
      'date': 'Date',
      'physical symptoms': 'Physical symptoms',
      'emotional symptoms': 'Emotional symptoms',

      'symptoms saved': 'Symptoms saved successfully.',
      'physical bauchschmerzen': 'Abdominal pain',
      'physical kopfschmerzen': 'Headache',
      'physical mudigkeit': 'Fatigue',
      'physical ubelkeit': 'Nausea',

      'emotional gereiztheit': 'Irritability',
      'emotional traurigkeit': 'Sadness',
      'emotional gelassenheit': 'Calmness',
      'emotional glucklich': 'Happiness',
      'emotional libido': 'Libido',

      'ausfluss cremig': 'Creamy',
      'ausfluss klebrig': 'Sticky',
      'ausfluss grau': 'Gray',
      'ausfluss geruchslos': 'Odorless',
      'ausfluss mit geruch': 'With odor',

      'flux wenig': 'Light',
      'flux normal': 'Normal',
      'flux stark': 'Heavy',
      'show more': 'Show more',
      'show less': 'Show less',
      'editing period': 'You are currently editing a period',

      'delete_confirm': 'Yes, delete',
      'period_deleted': 'Period deleted.',
      'edit_mode_activated': 'Edit mode activated – select a new date.',

      'moonflow': 'MoonFlow',
      'delete': 'Delete',
      'edit_period': 'Edit period',
      'select_start_end': 'Select the start and end date of your period',
      'period_saved': 'Period saved.',
      'period_exists': 'This period already exists.',
      'legend': 'Legend',
      'confirm_delete': 'Do you really want to delete this period?',
      'delete_period_title': 'Delete Confirmation',
      'period_selected': 'Period selected',
      'edit_or_delete':
          'Do you want to edit or delete the period from {start} to {end}?',
      "legend_period": "Period",
      "legend_ovulation": "Ovulation",
      "legend_fertile": "Fertile",
      "legend_selected": "Selected",
      "sort_newest": "Newest",
      "sort_oldest": "Oldest",
      "sort_most_liked": "Most Liked",
      "sort_my_comments": "My Comments",
      "comments": "Comments",
      "no_comments": "No comments... make a comment",

      "failed_post_comment": "Failed to post comment",
      //"you_are_in_fertile_window": "Du bist in deiner fruchtbaren Phase."
      "offline_mode": "Offline mode – changes will sync later",
      "online_mode": "Back online – syncing started",
    },
    'de': {
      "offline_mode": "Offline Modus – Änderungen werden später synchronisiert",
      "online_mode": "Wieder online – Synchronisierung gestartet",
      "sort_newest": "Neueste",
      "sort_oldest": "Älteste",
      "sort_most_liked": "Am meisten geliked",
      "sort_my_comments": "Meine Kommentare",
      "comments": "Kommentare",
      "no_comments": "Noch keine Kommentare... Schreibe einen!",
      "type_message": "Nachricht eingeben...",
      "error": "Fehler",
      "failed_post_comment": "Kommentar konnte nicht gesendet werden",

      "edit_period": "Periode bearbeiten",
      "legend": "Legende",
      "legend_period": "Periode",
      "legend_ovulation": "Eisprung",
      "legend_fertile": "Fruchtbar",
      "legend_selected": "Ausgewählt",

      'delete_confirm': 'Ja, löschen',
      'period_deleted': 'Periode gelöscht.',
      'edit_mode_activated':
          'Bearbeitungsmodus aktiviert – wähle ein neues Datum.',

      'moonflow': 'MoonFlow',
      'delete': 'Löschen',
      'select_start_end': 'Wähle den Start- und Endtag deiner Periode',
      'period_saved': 'Periode gespeichert.',
      'period_exists': 'Diese Periode existiert bereits.',
      'confirm_delete': 'Möchtest du diese Periode wirklich löschen?',
      'delete_period_title': 'Bestätigung',
      'period_selected': 'Periode ausgewählt',
      'edit_or_delete':
          'Möchtest du die Periode vom {start} bis {end} bearbeiten oder löschen?',

      'language': 'Sprache',
      'home': 'Startseite',
      'profile': 'Profil',
      'settings': 'Einstellungen',
      'logout': 'Abmelden',
      'dark_mode': 'Dunkler Modus',
      'change_period': 'Periode ändern',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'edit': 'Bearbeiten',
      'selected': 'Ausgewählt',
      'period': 'Periode',
      'ovulation': 'Eisprung',
      'fertile': 'Fruchtbar',
      'welcome': 'Willkommen',
      'enter_cycle_info': 'Lass uns gemeinsam deinen Zyklus besser verstehen!',
      'learn_about_cycle': 'Lerne deinen Zyklus kennen',
      'next': 'Weiter',
      'back': 'Zurück',
      'close': 'Schließen',
      'select_date': 'Datum auswählen',
      'invalid_number': 'Bitte gib eine gültige Zahl ein.',
      'fill_fields': 'Bitte fülle alle Felder aus.',
      'open calender': 'Periode eintragen',
      'reset': 'Zurücksetzen',
      'last symptom entry': 'Letzter Symptomeintrag',
      'view': 'Ansehen',
      'enter_symptom': 'Symptome eintragen',
      'enter_symptom_hint': 'Klicke hier, um deine Symptome hinzuzufügen',
      'cycle_duration': 'Zyklusdauer',
      'period_length': 'Periode',
      'next_ovulation': 'Nächster Eisprung',
      'fertile_window': 'Fruchtbare Phase',
      "last_period": "Letzte Periode",
      "to": "bis",
      "next_period_in": "Nächste Periode in {days} Tagen.",
      "you_are_in_your_period": "Du bist in deiner Periode.",
      "today_is_ovulation_day": "Heute ist dein Eisprung.",
      "you_are_fertile_in": "Fruchtbare Phase. Eisprung in {days} Tagen.",
      "days_until_next_period": "Tage bis zur nächsten Periode: {days}",
      'forum': 'Forum',
      'newest': 'Neueste',
      'oldest': 'Älteste',
      'most_liked': 'Meist geliked',
      'most_commented': 'Meist kommentiert',
      'my_posts': 'Meine Beiträge',
      'no_posts': 'Keine Beiträge... Schreib etwas',
      "search_posts": "Beiträge durchsuchen...",
      "chat_title": "Moonflow Chat Bot",
      "chat_hint": "Hallo, ich bin MoonFlowBot. Stelle deine Frage",
      "error_loading_response": "Fehler beim Laden der Antwort",
      "partner_mode": "Partner-Modus",
      "partner_title": "MoonFlow für Partner",
      "partner_welcome": "Schön, dass es dich gibt 💜",
      "partner_mood_prompt":
          "Wähle die Stimmung aus, die dein Partner sehen wird:",
      "mood_stars": "Sternenhimmel ✨",
      "mood_sunset": "Sonnenuntergang 🌅",
      "mood_glitch": "Futur Glitch 🌐",
      "generate_code": "🔗 Verbindungscode erstellen",
      "your_partner_code": "Dein Code für euren gemeinsamen Modus:",
      "share_code_message":
          "Teile diesen Code mit deinem Partner und lass ihn sehen, wie du dich fühlst 💫",
      "preview_partner_see":
          "So wird es auf dem Handy deines Partners aussehen",
      'no symptoms saved': 'Keine Symptome gespeichert.',
      'physical': 'Physisch',
      'emotional': 'Emotional',
      'discharge': 'Ausfluss',
      'flow': 'Flux',
      'enter symptoms': 'Symptome eintragen',
      'date': 'Datum',
      'physical symptoms': 'Physische Symptome',
      'emotional symptoms': 'Emotionale Symptome',

      'symptoms saved': 'Symptome erfolgreich gespeichert.',
      'physical bauchschmerzen': 'Bauchschmerzen',
      'physical kopfschmerzen': 'Kopfschmerzen',
      'physical mudigkeit': 'Müdigkeit',
      'physical ubelkeit': 'Übelkeit',

      'emotional gereiztheit': 'Gereiztheit',
      'emotional traurigkeit': 'Traurigkeit',
      'emotional gelassenheit': 'Gelassenheit',
      'emotional glucklich': 'Glücklich',
      'emotional libido': 'Libido',

      'ausfluss cremig': 'Cremig',
      'ausfluss klebrig': 'Klebrig',
      'ausfluss grau': 'Grau',
      'ausfluss geruchslos': 'Geruchslos',
      'ausfluss mit_geruch': 'Mit Geruch',

      'flux wenig': 'Wenig',
      'flux normal': 'Normal',
      'flux stark': 'Stark',
      'show more': 'Mehr anzeigen',
      'show less': 'Weniger anzeigen',
      'editing period': 'Du bearbeitest gerade eine Periode',

      //'you_are_in_fertile_window': 'Du bist in deiner fruchtbaren Phase.'
    },
  };

  static String translate(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    return _localizedValues[locale]?[key] ?? key;
  }
}
